version: "3.6"
services:
  shinyproxy:
    image: datanovia/shinyproxy
    container_name: dnv_shinyproxy
    restart: on-failure
    build: ./shinyproxy
    networks:
      - dnv-net
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
  euler:
    image: euler-docker
    container_name: dnv_euler
    build: ./shinyapps/euler-docker
    networks:
      - dnv-net

networks:
  dnv-net:
    name: dnv-net
